local m = peripheral.wrap( "top" )
local demo = true
local loopdelay = 0.3

function Start()
  m.setCursorPos(1,1)
  m.write("                                                           ")
  m.setCursorPos(1,2)
  m.write("                                                           ")
  m.setCursorPos(1,3)
  m.write("        \\")
  m.setCursorPos(1,4)
  m.write(" _      ||__________________")
  m.setCursorPos(1,5)
  m.write("(_|%|%|%|[__________________>")
  m.setCursorPos(1,6)
  m.write("        ||")
  m.setCursorPos(1,7)
  m.write("         \\")
  m.setCursorPos(1,8)
  m.write("                                                           ")
  m.setCursorPos(1,9)
  m.write("-= Nitro's Arena =- ")
  m.setCursorPos(1,10)
  m.write("This Arena has been built so that you can challenge other players to fight to the")
  m.setCursorPos(1,11)
  m.write("death for their loot")
  m.setCursorPos(1,12)
  m.write("Rules:")
  m.setCursorPos(1,13)
  m.write("- To Start The Game you need at least 2 players.")
  m.setCursorPos(1,14)
  m.write("- You cannot bring external tools/weapons into the battle area")
  m.setCursorPos(1,15)
  m.write("- You cannot break blocks or exploit the map")
  m.setCursorPos(1,16)
  m.write("- Both players must accept the other's bet before the game can start")
  m.setCursorPos(1,17)
  m.write("- You must have the key item in your inventory while alive in the arena")
  m.setCursorPos(1,18)
  m.write("- Once you win you need to use the keys at the gate on one of the walls to collect")
  m.setCursorPos(1,19)
  m.write("your loot")
  m.setCursorPos(1,20)
  m.write("- You will be provided with weapons before the match so that the battle is fair")
  m.setCursorPos(1,21)
  m.write("- You Must collect all keys from other players by killing them")



  while demo == true do
    m.setCursorPos(1,1)
    m.write("-= Arena =-")
    sleep(loopdelay)
    m.setCursorPos(1,4)
    m.write(" _      ||__________________")
    m.setCursorPos(1,1)
    m.write("-=  rena =-")
    m.setCursorPos(1,4)
    m.write(" _      ||________________x_")
    sleep(loopdelay)
    m.setCursorPos(1,4)
    m.write(" _      ||________________+_")
    m.setCursorPos(1,1)
    m.write("-=   ena =-")
    sleep(loopdelay)
    m.setCursorPos(1,4)
    m.write(" _      ||__________________")
    m.setCursorPos(1,5)
    m.write("(_|%|%|%|[______+___________>")
    m.setCursorPos(1,1)
    m.write("-=    na =-")
    sleep(loopdelay)
    m.setCursorPos(1,5)
    m.write("(_|%|%|%|[______x___________>")
    m.setCursorPos(1,1)
    m.write("-=     a =-")
    sleep(loopdelay)
    m.setCursorPos(1,5)
    m.write("(_|%|%|%|[__________________>")
    m.setCursorPos(1,1)
    m.write("-=       =-")
    sleep(loopdelay)
    m.setCursorPos(1,1)
    m.write("-= A     =-")
    sleep(loopdelay)
    m.setCursorPos(1,1)
    m.write("-= Ar    =-")
    sleep(loopdelay)
    m.setCursorPos(1,4)
    m.write(" _      ||_x________________")
    m.setCursorPos(1,1)
    m.write("-= Are   =-")
    sleep(loopdelay)
    m.setCursorPos(1,4)
    m.write(" _      ||_+________________")
    m.setCursorPos(1,1)
    m.write("-= Aren  =-")
    sleep(loopdelay)
  end
  m.setCursorPos(1,1)
  m.write("-= Arena =-")
end

Start()
