term.clear()
local monitor = peripheral.wrap("top")
monitor.setTextColor(colors.green)
term.setTextColor(colors.green)
print("Loading...")
monitor.clear()
monitor.setCursorPos(1,1)
monitor.write("Loading...")
redstone.setOutput("back", true)
monitor.setCursorPos(1,2)
sleep(1)
print("1%")
monitor.write("1%")
redstone.setOutput("back", false)
sleep(1)
monitor.setCursorPos(1,3)
print("2%")
monitor.write("2%")
sleep(1)
monitor.setCursorPos(1,4)
print("3%")
monitor.write("3%")
sleep(1)
monitor.setCursorPos(1,5)
print("4%")
monitor.write("4%")
monitor.setCursorPos(1,6)
sleep(1)
print("5%")
monitor.write("5%")
monitor.setCursorPos(1,7)
sleep(1)
print("11%")
monitor.write("11%")
monitor.setCursorPos(1,8)
sleep(0.5)
print("24%")
monitor.write("24%")
monitor.setCursorPos(1,9)
sleep(0.5)
print("37%")
monitor.write("37%")
monitor.setCursorPos(1,10)
sleep(0.75)
print("48%")
monitor.write("48%")
monitor.setCursorPos(1,11)
sleep(0.5)
print("57%")
monitor.write("57%")
monitor.setCursorPos(1,12)
sleep(0.5)
print("63%")
monitor.write("63%")
monitor.setCursorPos(1,13)
sleep(0.5)
monitor.clear()
monitor.setCursorPos(1,1)
print("75%")
monitor.write("75%")
monitor.setCursorPos(1,2)
sleep(0.5)
print("84%")
monitor.write("84%")
monitor.setCursorPos(1,3)
sleep(0.5)
print("Potato")
monitor.write("Potato")
monitor.setCursorPos(1,4)
sleep(0.5)
print("99%")
monitor.write("99%")
monitor.setCursorPos(1,5)
sleep(2)
print("100%")
monitor.write("100%")
monitor.setCursorPos(1,6)
sleep(5)
print("Loading Complete")
monitor.write("Loading Complete")
monitor.setCursorPos(1,7)
sleep(0.5)
print("Clearing Screen And Booting OS")
monitor.write("Clearing Screen And Booting OS")
monitor.setCursorPos(1,8)
sleep(4)
term.clear()
monitor.clear()
monitor.setCursorPos(1,1)
monitor.setTextColor(colors.green)
term.setTextColor(colors.green)
textutils.slowPrint("TNT OS [Version 6.1.76]")
monitor.write("TNT OS [Verion 6.1.76]")
monitor.setCursorPos(1,2)
textutils.slowPrint("Copyright <c> 2015 MB TNT Inc. All rights Reserved.")
monitor.write("Copyright <c> 2015 MB TNT Inc.")
term.setTextColor(colors.white)
monitor.setTextColor(colors.white)
monitor.setCursorPos(1,4)
sleep(0.5)
print("          *    ")
monitor.write("          *")
monitor.setCursorPos(1,5)
sleep(0.5)
print("          |    ")
monitor.write("         |")
monitor.setCursorPos(1,6)
sleep(0.5)
print("         -     ")
monitor.write("         _")
monitor.setCursorPos(1,7)
sleep(0.5)
print("        |      ")
monitor.write("        |")
monitor.setCursorPos(1,8)
sleep(0.5)
term.setTextColor(colors.red)
monitor.setTextColor(colors.red)
sleep(0.5)
print("###################")
monitor.write("###################")
monitor.setCursorPos(1,9)
sleep(0.5)
print("##___###___###___##")
monitor.write("##___###___###___##")
monitor.setCursorPos(1,10)
sleep(0.5)
print("#|_ _|#|   |#|_ _|#")
monitor.write("#|_ _|#|   |#|_ _|#")
monitor.setCursorPos(1,11)
sleep(0.5)
print("##| |##| | |##| |##")
monitor.write("##| |##| | |##| |##")
monitor.setCursorPos(1,12)
sleep(0.5)
print("##|_|##|_|_|##|_|##")
monitor.write("##|_|##|_|_|##|_|##")
monitor.setCursorPos(1,13)
sleep(0.5)
print("###################")
monitor.write("###################")
